/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifcvideira.Lista10;

import javax.swing.DefaultListModel;

/**
 *
 * @author Eduardo Ugolini <edu.ugolini2@gmail.com>
 */
public class Exercicio4 extends javax.swing.JFrame {
    /**
     * Creates new form Exercicio4
     */
    public Exercicio4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        floatLabel = new javax.swing.JLabel();
        nameFieldText = new javax.swing.JTextField();
        ageFieldText = new javax.swing.JTextField();
        typeCombobox = new javax.swing.JComboBox();
        dynamicLabel = new javax.swing.JLabel();
        dynamicTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        finalList = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nameLabel.setText("Nome: ");

        ageLabel.setText("Idade: ");

        typeLabel.setText("Tipo Pessoa: ");

        typeCombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Colega de Trabalho", "Amigo", "Parente" }));
        typeCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeComboboxActionPerformed(evt);
            }
        });

        dynamicLabel.setText("Setor: ");

        dynamicTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dynamicTextFieldActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(finalList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(dynamicLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nameLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ageLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(typeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(floatLabel, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameFieldText)
                            .addComponent(ageFieldText)
                            .addComponent(typeCombobox, 0, 281, Short.MAX_VALUE)
                            .addComponent(dynamicTextField))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameFieldText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ageLabel)
                    .addComponent(ageFieldText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(floatLabel))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dynamicTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dynamicLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void typeComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeComboboxActionPerformed
        if(typeCombobox.getSelectedItem().toString().equals("Colega de Trabalho")){
            dynamicLabel.setText("Setor: ");
        }
        else if(typeCombobox.getSelectedItem().toString().equals("Amigo")){
            dynamicLabel.setText("Telefone Pessoal: ");
        }else{
            dynamicLabel.setText("Parentesco: ");
        }
    }//GEN-LAST:event_typeComboboxActionPerformed

    private void dynamicTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dynamicTextFieldActionPerformed
        if(typeCombobox.getSelectedItem().toString().equals("Colega de Trabalho")){
            printColega();
        }
        else if(typeCombobox.getSelectedItem().toString().equals("Amigo")){
            printAmigo();
        }
        else{
            printParente();
        }
    }//GEN-LAST:event_dynamicTextFieldActionPerformed

    private void printColega(){
        Colega_de_trabalho colega = new Colega_de_trabalho();
        colega.setNome(nameFieldText.getText());
        colega.setIdade(Integer.parseInt(ageFieldText.getText()));
        colega.setSetor(dynamicTextField.getText());
        
        DefaultListModel modelList = new DefaultListModel();
        modelList.addElement(colega.getNome());
        modelList.addElement(colega.getIdade());
        modelList.addElement(typeCombobox.getSelectedItem());
        modelList.addElement(colega.getSetor());
        modelList.addElement(colega.getAssinatura());
        finalList.setModel(modelList);
    }
    
    private void printAmigo(){
        Amigo amigo = new Amigo();
        amigo.setNome(nameFieldText.getText());
        amigo.setIdade(Integer.parseInt(ageFieldText.getText()));
        amigo.setTelefonePessoal(dynamicTextField.getText());
        
        DefaultListModel modelList = new DefaultListModel();
        modelList.addElement(amigo.getNome());
        modelList.addElement(amigo.getIdade());
        modelList.addElement(typeCombobox.getSelectedItem());
        modelList.addElement(amigo.getTelefonePessoal());
        modelList.addElement(amigo.getAssinatura());
        finalList.setModel(modelList);
    }
    
    private void printParente(){
        Parente parente = new Parente();
        parente.setNome(nameFieldText.getText());
        parente.setIdade(Integer.parseInt(ageFieldText.getText()));
        parente.setParentesco(dynamicTextField.getText());
        
        DefaultListModel modelList = new DefaultListModel();
        modelList.addElement(parente.getNome());
        modelList.addElement(parente.getIdade());
        modelList.addElement(typeCombobox.getSelectedItem());
        modelList.addElement(parente.getParentesco());
        modelList.addElement(parente.getAssinatura());
        finalList.setModel(modelList);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercicio4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercicio4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercicio4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercicio4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exercicio4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageFieldText;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JLabel dynamicLabel;
    private javax.swing.JTextField dynamicTextField;
    private javax.swing.JList finalList;
    private javax.swing.JLabel floatLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameFieldText;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JComboBox typeCombobox;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
}
