/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifcvideira.Lista8;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Eduardo Ugolini <edu.ugolini2@gmail.com>
 */
public class Exercicio1 extends javax.swing.JFrame {

    /**
     * Creates new form Exercicio1
     */
    public Exercicio1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeFuncionario = new javax.swing.JLabel();
        cargoFuncionario = new javax.swing.JLabel();
        salarioFuncionario = new javax.swing.JLabel();
        turnoFuncionario = new javax.swing.JLabel();
        cargo = new javax.swing.JComboBox();
        adicionar = new javax.swing.JButton();
        turno = new javax.swing.JComboBox();
        nome = new javax.swing.JTextField();
        salario = new javax.swing.JTextField();
        matriculaFuncionario = new javax.swing.JLabel();
        matricula = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaCadastros = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nomeFuncionario.setText("Nome");

        cargoFuncionario.setText("Cargo");

        salarioFuncionario.setText("Salário");

        turnoFuncionario.setText("Turno");

        cargo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gerente", "Assistente Técnico", "Assistente Administrativo" }));
        cargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargoActionPerformed(evt);
            }
        });

        adicionar.setText("Calcular");
        adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarFuncionario(evt);
            }
        });

        turno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Diurno", "Noturno" }));
        turno.setEnabled(false);

        matriculaFuncionario.setText("Matrícula");

        matricula.setEnabled(false);

        jScrollPane1.setViewportView(listaCadastros);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(matriculaFuncionario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(matricula))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(turnoFuncionario)
                                .addGap(18, 18, 18)
                                .addComponent(turno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(salarioFuncionario)
                                .addGap(18, 18, 18)
                                .addComponent(salario))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cargoFuncionario)
                                .addGap(18, 18, 18)
                                .addComponent(cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nomeFuncionario)
                                .addGap(18, 18, 18)
                                .addComponent(nome)))
                        .addGap(62, 62, 62)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomeFuncionario)
                            .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cargoFuncionario)
                            .addComponent(cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salarioFuncionario)
                            .addComponent(salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(turnoFuncionario)
                            .addComponent(turno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(matriculaFuncionario)
                            .addComponent(matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(adicionar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adicionarFuncionario(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarFuncionario
        String cargoCadastrado = cargo.getSelectedItem().toString();

        if(cargoCadastrado == "Gerente"){
            newGerente();
        }
        else if(cargoCadastrado == "Assistente Técnico"){
            newAssistenteTecnico();
        }else{
            newAssistenteAdministrativo();
        }
    }//GEN-LAST:event_adicionarFuncionario

    private void cargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargoActionPerformed
        if(cargo.getSelectedItem().toString() == "Assistente Administrativo"){
            turno.setEnabled(true);
            matricula.setEnabled(true);
        }
        else{
            turno.setEnabled(false);
            matricula.setEnabled(false);
        }
    }//GEN-LAST:event_cargoActionPerformed
   
    private void newGerente(){
        Gerente gerente = new Gerente();
        try{
            gerente.setNome(nome.getText());
            gerente.setSalario(Double.parseDouble(salario.getText()));
            gerente.setCargo(cargo.getSelectedItem().toString());
            printGerenteResults(gerente);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        }
    }
    
    private void newAssistenteTecnico(){
        AssistenteTecnico aTecnico = new AssistenteTecnico();
        
        try{
            aTecnico.setNome(nome.getText());
            aTecnico.setSalario(Double.parseDouble(salario.getText()));
            aTecnico.setCargo(cargo.getSelectedItem().toString());
            printATecnicoResults(aTecnico);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        }
    }
    
    private void newAssistenteAdministrativo(){
        AssistenteAdministrativo aAdministrativo = new AssistenteAdministrativo();
        
        try{
            aAdministrativo.setNome(nome.getText());
            aAdministrativo.setSalario(Double.parseDouble(salario.getText()));
            aAdministrativo.setCargo(cargo.getSelectedItem().toString());
            aAdministrativo.setMatricula(Integer.parseInt(matricula.getText()));
            printAAdministrativoResults(aAdministrativo);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        }
    }
    
    private void printGerenteResults(Object sender){
        DefaultListModel gettersList = new DefaultListModel();
        Gerente gerente = (Gerente) sender;
        gettersList.addElement("Nome: " + gerente.getNome());
        gettersList.addElement("Cargo: " + gerente.getCargo());
        gettersList.addElement("Salário + Bônus: " + gerente.getSalarioEBonus());
        
        listaCadastros.setModel(gettersList);
    }
    
    private void printATecnicoResults(Object sender){
        DefaultListModel gettersList = new DefaultListModel();
        
        AssistenteTecnico aTecnico = (AssistenteTecnico) sender;
        gettersList.addElement("Nome: " + aTecnico.getNome());
        gettersList.addElement("Cargo: " + aTecnico.getCargo());
        gettersList.addElement("Salário + Bônus: " + aTecnico.getSalarioEBonus());
        
        listaCadastros.setModel(gettersList);
    }
    
    private void printAAdministrativoResults(Object sender){
        DefaultListModel gettersList = new DefaultListModel();
        
        AssistenteAdministrativo aAdministrativo = (AssistenteAdministrativo) sender;
        gettersList.addElement("Nome: " + aAdministrativo.getNome());
        gettersList.addElement("Cargo: " + aAdministrativo.getCargo());
        
        if(turno.getSelectedItem().toString() == "Noturno"){
            gettersList.addElement("Salário + Bônus: " + aAdministrativo.getSalarioEBonusNoturno());
        }else{
            gettersList.addElement("Salário: " + aAdministrativo.getSalario());
        }
        
        gettersList.addElement("Matrícula: " + aAdministrativo.getMatricula());
        
        listaCadastros.setModel(gettersList);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exercicio1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionar;
    private javax.swing.JComboBox cargo;
    private javax.swing.JLabel cargoFuncionario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listaCadastros;
    private javax.swing.JTextField matricula;
    private javax.swing.JLabel matriculaFuncionario;
    private javax.swing.JTextField nome;
    private javax.swing.JLabel nomeFuncionario;
    private javax.swing.JTextField salario;
    private javax.swing.JLabel salarioFuncionario;
    private javax.swing.JComboBox turno;
    private javax.swing.JLabel turnoFuncionario;
    // End of variables declaration//GEN-END:variables
}
