/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifcvideira.Lista8;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Eduardo Ugolini <edu.ugolini2@gmail.com>
 */
public class Exercicio2 extends javax.swing.JFrame {

    private Cachorro cachorro;
    private Gato gato;
    
    /**
     * Creates new form Exercicio2
     */
    public Exercicio2() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        late = new javax.swing.JButton();
        mia = new javax.swing.JButton();
        nomeAnimal = new javax.swing.JTextField();
        racaAnimal = new javax.swing.JComboBox();
        latidas = new javax.swing.JLabel();
        miadas = new javax.swing.JLabel();
        andando = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome: ");

        jLabel2.setText("Raça");

        late.setText("Late");
        late.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                latindo(evt);
            }
        });

        mia.setText("Mia");
        mia.setEnabled(false);
        mia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miando(evt);
            }
        });

        nomeAnimal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                criaBicho(evt);
            }
        });

        racaAnimal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cachorro", "Gato" }));
        racaAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionaRaca(evt);
            }
        });

        latidas.setText("O cachorro latiu 0 vezes");

        miadas.setText("O gato miou 0 vezes");

        andando.setText("Andando");
        andando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mudouEstado(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(miadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(latidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(andando))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(late, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(mia, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeAnimal)
                            .addComponent(racaAnimal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomeAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(racaAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(late)
                    .addComponent(mia))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(latidas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(andando))
                .addGap(18, 18, 18)
                .addComponent(miadas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void latindo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_latindo
        fezSom(false);
        latidas.setText("O cachorro " + cachorro.getNome() +" latiu " + cachorro.getLatidas() + " vezes");
    }//GEN-LAST:event_latindo

    private void miando(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miando
        fezSom(true);
        miadas.setText("O gato " + gato.getNome() + " miou " + gato.getMiadas() + " vezes");
    }//GEN-LAST:event_miando

    private void selecionaRaca(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionaRaca
        if(racaAnimal.getSelectedItem().toString() == "Cachorro"){
            cachorro = new Cachorro(nomeAnimal.getText());
            late.setEnabled(true);
            mia.setEnabled(false);
        }else{
            gato = new Gato(nomeAnimal.getText());
            late.setEnabled(false);
            mia.setEnabled(true);
        }
    }//GEN-LAST:event_selecionaRaca

    private void criaBicho(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_criaBicho
        if(racaAnimal.getSelectedItem().toString() == "Cachorro"){
            cachorro = new Cachorro(nomeAnimal.getText());
        }else{
            gato = new Gato(nomeAnimal.getText());
        }
    }//GEN-LAST:event_criaBicho

    private void mudouEstado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mudouEstado
        try{
            if(racaAnimal.getSelectedItem().toString() == "Cachorro"){
                cachorro.changeEstado();
            }else{
                gato.changeEstado();
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        }
    }//GEN-LAST:event_mudouEstado

    private void fezSom(boolean som){
        //False representa o latido, e true, representa o miado
        try{
            if(som == false){
                cachorro.late();
            }
            else{
                gato.mia();
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exercicio2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton andando;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton late;
    private javax.swing.JLabel latidas;
    private javax.swing.JButton mia;
    private javax.swing.JLabel miadas;
    private javax.swing.JTextField nomeAnimal;
    private javax.swing.JComboBox racaAnimal;
    // End of variables declaration//GEN-END:variables
}
